-- PKWT archive — struktur folder HRIS PKWT / <Bulan Tahun> / <KODE PERUSAHAAN>
-- Jalankan file ini sekali di Supabase SQL Editor (project yang sama dengan
-- NEXT_PUBLIC_SUPABASE_URL). Aman dijalankan ulang (idempotent).
--
-- Isi:
-- 1. drive_folders      — cache ID folder Drive per (parent, nama) supaya
--                          serverless tidak pernah membuat folder kembar.
-- 2. document_logs      — kolom audit lokasi arsip (folder_id / folder_path).
--
-- Catatan: bila file ini belum dijalankan, aplikasi TETAP jalan — cache folder
-- dilewati (list/create langsung ke Drive) dan insert log fallback ke skema lama.

-- ============ 1. Cache folder Drive ============
create table if not exists drive_folders (
  id bigint generated by default as identity primary key,
  parent_id text not null,
  name text not null,
  folder_id text not null default '',
  created_at timestamp with time zone not null default now(),
  unique (parent_id, name)
);

-- ============ 2. document_logs: lokasi arsip ============
alter table document_logs add column if not exists folder_id text;
alter table document_logs add column if not exists folder_path text;
